services:
  - type: web
    name: waste-recycling-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

